reporter: "mocha-w3c-interop-reporter"
reporterOptions:
  - 'title=DID Resolution Test Suite'
  - 'abstract=./abstract.hbs'
  - 'reportDir=./reports'
  - 'respec=./respecConfig.json'
  - 'suiteLog=./suite.log'
  - 'templateData=./reports/index.json'
